name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker pull ghcr.io/ollytheninja/flick-exporter:latest
        docker build . --file Dockerfile --tag flick-exporter:latest

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: pull docker images for cache
      run: docker pull ghcr.io/ollytheninja/flick-exporter:latest

    - name: Build and push image
      run: |
        git fetch
        git pull --tags
        export DATESTAMP=$(date +%s)
        export VERSION=$(git describe --tags)
        docker tag flick-exporter:latest ghcr.io/ollytheninja/flick-exporter:$DATESTAMP
        docker tag flick-exporter:latest ghcr.io/ollytheninja/flick-exporter:$VERSION
        docker tag flick-exporter:latest ghcr.io/ollytheninja/flick-exporter:latest

        docker push ghcr.io/ollytheninja/flick-exporter:$DATESTAMP
        docker push ghcr.io/ollytheninja/flick-exporter:$VERSION
        docker push ghcr.io/ollytheninja/flick-exporter:latest
