name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flick-exporter:latest

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: pull tags
      run: git pull --tags

    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v1
      with:
        include: 'v*'
        commit-ish: 'HEAD'

    - name: Push image
      run: |
        export DATESTAMP=$(date +%s)
        export VERSION=${{steps.tagger.outputs.tag}}
        docker tag flick-exporter:latest ghcr.io/ollytheninja/flick-exporter:$DATESTAMP
        docker tag flick-exporter:latest ghcr.io/ollytheninja/flick-exporter:$VERSION
        docker tag flick-exporter:latest ghcr.io/ollytheninja/flick-exporter:latest

        docker push ghcr.io/ollytheninja/flick-exporter:$DATESTAMP
        docker push ghcr.io/ollytheninja/flick-exporter:$VERSION
        docker push ghcr.io/ollytheninja/flick-exporter:latest
